import type { PetListing } from '@/types/pet';

const unsplash = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=70`;

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 3_600_000).toISOString();

/**
 * Publicaciones semilla. En producción vendrían de la API;
 * aquí viven aparte para que la galería no dependa de la capa de datos.
 */
export const SEED_LISTINGS: PetListing[] = [
  {
    id: 'seed-luna',
    slug: 'luna-miraflores',
    name: 'Luna',
    species: 'perro',
    sex: 'hembra',
    ageLabel: '3 años',
    size: 'mediano',
    city: 'Miraflores',
    photoUrl: unsplash('photo-1543466835-00a7907e9de1'),
    photoAlt: 'Luna, beagle marrón y blanca, con la boca abierta y las orejas caídas en un parque',
    highlight: 'Le encantan los niños',
    description:
      'Luna es pura energía buena. Camina bien con correa, sabe sentarse y dar la pata, y duerme a los pies de la cama. Busca una familia activa que la saque a pasear todos los días.',
    health: { sterilized: true, vaccinated: true, dewormed: true, microchip: true },
    idealHome: 'casa-con-patio',
    goodWithKids: true,
    goodWithPets: true,
    status: 'con-interesados',
    interestedCount: 7,
    publishedAt: hoursAgo(5),
  },
  {
    id: 'seed-milo',
    slug: 'milo-san-isidro',
    name: 'Milo',
    species: 'gato',
    sex: 'macho',
    ageLabel: '2 años',
    size: 'pequeno',
    city: 'San Isidro',
    photoUrl: unsplash('photo-1514888286974-6c03e2ca1dba'),
    photoAlt: 'Milo, gato blanco y negro de ojos verdes, apoyado sobre una repisa de madera',
    highlight: 'Tranquilo, ideal para departamento',
    description:
      'Milo es un gato de ventana y sillón. Usa el arenero sin problemas y se deja agarrar. Le cuesta un poco con perros, pero con otros gatos convive bien.',
    health: { sterilized: true, vaccinated: true, dewormed: true, microchip: false },
    idealHome: 'departamento',
    goodWithKids: true,
    goodWithPets: false,
    status: 'publicada',
    interestedCount: 3,
    publishedAt: hoursAgo(9),
  },
  {
    id: 'seed-nube',
    slug: 'nube-barranco',
    name: 'Nube',
    species: 'conejo',
    sex: 'hembra',
    ageLabel: '1 año',
    size: 'pequeno',
    city: 'Barranco',
    photoUrl: unsplash('photo-1585110396000-c9ffd4e4b308'),
    photoAlt: 'Nube, conejo blanco de orejas largas, sentado sobre el pasto',
    highlight: 'Ya usa su rincón sanitario',
    description:
      'Nube es curiosa y muy limpia. Come heno, verduras de hoja y su alimento balanceado. Necesita un rato suelta por día para explorar.',
    health: { sterilized: false, vaccinated: true, dewormed: true, microchip: false },
    idealHome: 'departamento',
    goodWithKids: true,
    goodWithPets: false,
    status: 'publicada',
    interestedCount: 2,
    publishedAt: hoursAgo(22),
  },
  {
    id: 'seed-kiwi',
    slug: 'kiwi-surco',
    name: 'Kiwi',
    species: 'ave',
    sex: 'macho',
    ageLabel: '4 años',
    city: 'Surco',
    photoUrl: unsplash('photo-1552728089-57bdde30beb3'),
    photoAlt: 'Kiwi, periquito verde de pico naranja, posado en una rama',
    highlight: 'Canta a la mañana',
    description:
      'Kiwi es sociable y charlatán. Va con su jaula grande, comedero y bebedero. Ideal para alguien que pase tiempo en casa.',
    health: { sterilized: false, vaccinated: false, dewormed: true, microchip: false },
    idealHome: 'experiencia-previa',
    goodWithKids: true,
    goodWithPets: false,
    status: 'con-interesados',
    interestedCount: 5,
    publishedAt: hoursAgo(28),
  },
  {
    id: 'seed-otto',
    slug: 'otto-san-borja',
    name: 'Otto',
    species: 'perro',
    sex: 'macho',
    ageLabel: '5 años',
    size: 'pequeno',
    city: 'San Borja',
    photoUrl: unsplash('photo-1517849845537-4d257902454a'),
    photoAlt: 'Otto, pug negro con bufanda de lana, mirando a cámara sobre fondo amarillo',
    highlight: 'Compañero de sillón',
    description:
      'Otto ya encontró familia. Lo dejamos publicado para que veas cómo termina una historia en Homie.',
    health: { sterilized: true, vaccinated: true, dewormed: true, microchip: true },
    specialNeeds: 'Braquicéfalo: evitar ejercicio intenso con calor.',
    idealHome: 'departamento',
    goodWithKids: true,
    goodWithPets: true,
    status: 'adoptada',
    interestedCount: 11,
    publishedAt: hoursAgo(52),
  },
  {
    id: 'seed-canela',
    slug: 'canela-jesus-maria',
    name: 'Canela',
    species: 'gato',
    sex: 'hembra',
    ageLabel: '6 meses',
    size: 'pequeno',
    city: 'Jesús María',
    photoUrl: unsplash('photo-1573865526739-10659fec78a5'),
    photoAlt: 'Canela, gata naranja de pelo largo, estirada sobre una mesa de madera',
    highlight: 'Juguetona y sociable',
    description:
      'Canela persigue todo lo que se mueve y después se duerme encima tuyo. Tiene la primera dosis de vacunas y le falta la castración (la familia se compromete a hacerla).',
    health: { sterilized: false, vaccinated: true, dewormed: true, microchip: false },
    idealHome: 'departamento',
    goodWithKids: true,
    goodWithPets: true,
    status: 'publicada',
    interestedCount: 4,
    publishedAt: hoursAgo(31),
  },
  {
    id: 'seed-pipo',
    slug: 'pipo-pueblo-libre',
    name: 'Pipo',
    species: 'roedor',
    sex: 'macho',
    ageLabel: '1 año',
    city: 'Pueblo Libre',
    photoUrl: unsplash('photo-1425082661705-1834bfd09dca'),
    photoAlt: 'Pipo, hámster dorado sentado sobre sus patas traseras comiendo',
    highlight: 'Va con jaula y accesorios',
    description:
      'Pipo es nocturno y muy tranquilo de día. Va con jaula, rueda silenciosa y viruta para las primeras semanas.',
    health: { sterilized: false, vaccinated: false, dewormed: false, microchip: false },
    idealHome: 'departamento',
    goodWithKids: false,
    goodWithPets: false,
    status: 'publicada',
    interestedCount: 1,
    publishedAt: hoursAgo(40),
  },
  {
    id: 'seed-tomas',
    slug: 'tomas-la-molina',
    name: 'Tomás',
    species: 'perro',
    sex: 'macho',
    ageLabel: '4 meses',
    size: 'mediano',
    city: 'La Molina',
    photoUrl: unsplash('photo-1552053831-71594a27632d'),
    photoAlt: 'Tomás, cachorro golden retriever sosteniendo una flor en el hocico',
    highlight: 'Primera vacuna al día',
    description:
      'Tomás está aprendiendo a hacer sus necesidades afuera y a quedarse solo un rato. Es cachorro: muerde todo y necesita paciencia.',
    health: { sterilized: false, vaccinated: true, dewormed: true, microchip: false },
    idealHome: 'casa-con-patio',
    goodWithKids: true,
    goodWithPets: true,
    status: 'con-interesados',
    interestedCount: 9,
    publishedAt: hoursAgo(14),
  },
  {
    id: 'seed-mora',
    slug: 'mora-magdalena',
    name: 'Mora',
    species: 'gato',
    sex: 'hembra',
    ageLabel: '7 años',
    size: 'mediano',
    city: 'Magdalena del Mar',
    photoUrl: unsplash('photo-1495360010541-f48722b34f7d'),
    photoAlt: 'Mora, gata atigrada de pelo largo, sentada en una escalera blanca',
    highlight: 'Busca una casa sin ruido',
    description:
      'Mora vivió siempre con una señora mayor. Es cariñosa a su ritmo y necesita un hogar calmo, sin niños pequeños.',
    health: { sterilized: true, vaccinated: true, dewormed: true, microchip: true },
    specialNeeds: 'Alimento renal indicado por su veterinaria.',
    idealHome: 'departamento',
    goodWithKids: false,
    goodWithPets: false,
    status: 'publicada',
    interestedCount: 2,
    publishedAt: hoursAgo(60),
  },
  {
    id: 'seed-trufa',
    slug: 'trufa-lince',
    name: 'Trufa',
    species: 'conejo',
    sex: 'hembra',
    ageLabel: '2 años',
    size: 'mediano',
    city: 'Lince',
    photoUrl: unsplash('photo-1452857297128-d9c29adba80b'),
    photoAlt: 'Trufa, conejo belier beige de orejas caídas, sobre el césped',
    highlight: 'Se lleva bien con gatos',
    description:
      'Trufa creció con dos gatos y los adora. Es mimosa, se deja cepillar y conoce su nombre.',
    health: { sterilized: true, vaccinated: true, dewormed: true, microchip: false },
    idealHome: 'departamento',
    goodWithKids: true,
    goodWithPets: true,
    status: 'publicada',
    interestedCount: 3,
    publishedAt: hoursAgo(70),
  },
  {
    id: 'seed-iggy',
    slug: 'iggy-chorrillos',
    name: 'Iggy',
    species: 'reptil',
    sex: 'macho',
    ageLabel: '3 años',
    size: 'grande',
    city: 'Chorrillos',
    photoUrl: unsplash('photo-1504450874802-0ba2bcd9b5ae'),
    photoAlt: 'Iggy, iguana verde caminando sobre un piso claro',
    highlight: 'Terrario incluido',
    description:
      'Iggy va con su terrario de 1,5 m, lámpara UVB y calefactor. Come verduras frescas todos los días.',
    health: { sterilized: false, vaccinated: false, dewormed: true, microchip: false },
    specialNeeds: 'Necesita luz UVB y temperatura controlada (28–35 °C).',
    idealHome: 'experiencia-previa',
    goodWithKids: false,
    goodWithPets: false,
    status: 'publicada',
    interestedCount: 1,
    publishedAt: hoursAgo(85),
  },
];

/** Tamaño recomendado por WhatsApp/Facebook para la vista previa del enlace. */
export const ogImageFor = (photoUrl: string): string =>
  photoUrl.replace(/w=\d+/, 'w=1200').replace('fit=crop', 'fit=crop&h=630');

export function findListingBySlug(slug: string): PetListing | undefined {
  return SEED_LISTINGS.find((listing) => listing.slug === slug);
}
