import type { PetListing } from '@/types/pet';

const unsplash = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=70`;

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 3_600_000).toISOString();

/**
 * Publicaciones semilla. En producción vendrían de la API;
 * acá viven aparte para que la galería no dependa de la capa de datos.
 */
export const SEED_LISTINGS: PetListing[] = [
  {
    id: 'seed-luna',
    name: 'Luna',
    species: 'perro',
    ageLabel: '3 años',
    size: 'mediano',
    city: 'Córdoba',
    photoUrl: unsplash('photo-1543466835-00a7907e9de1'),
    photoAlt: 'Luna, beagle marrón y blanca, con la boca abierta y las orejas caídas en un parque',
    highlight: 'Le encantan los chicos',
    status: 'con-interesados',
    interestedCount: 7,
    publishedAt: hoursAgo(5),
  },
  {
    id: 'seed-milo',
    name: 'Milo',
    species: 'gato',
    ageLabel: '2 años',
    size: 'pequeno',
    city: 'Rosario',
    photoUrl: unsplash('photo-1514888286974-6c03e2ca1dba'),
    photoAlt: 'Milo, gato blanco y negro de ojos verdes, apoyado sobre una repisa de madera',
    highlight: 'Tranquilo, ideal para depto',
    status: 'publicada',
    interestedCount: 3,
    publishedAt: hoursAgo(9),
  },
  {
    id: 'seed-nube',
    name: 'Nube',
    species: 'conejo',
    ageLabel: '1 año',
    size: 'pequeno',
    city: 'La Plata',
    photoUrl: unsplash('photo-1585110396000-c9ffd4e4b308'),
    photoAlt: 'Nube, conejo blanco de orejas largas, sentado sobre el pasto',
    highlight: 'Ya usa su rincón sanitario',
    status: 'publicada',
    interestedCount: 2,
    publishedAt: hoursAgo(22),
  },
  {
    id: 'seed-kiwi',
    name: 'Kiwi',
    species: 'ave',
    ageLabel: '4 años',
    size: 'pequeno',
    city: 'Mendoza',
    photoUrl: unsplash('photo-1552728089-57bdde30beb3'),
    photoAlt: 'Kiwi, periquito verde de pico naranja, posado en una rama',
    highlight: 'Canta a la mañana',
    status: 'con-interesados',
    interestedCount: 5,
    publishedAt: hoursAgo(28),
  },
  {
    id: 'seed-otto',
    name: 'Otto',
    species: 'perro',
    ageLabel: '5 años',
    size: 'pequeno',
    city: 'Buenos Aires',
    photoUrl: unsplash('photo-1517849845537-4d257902454a'),
    photoAlt: 'Otto, pug negro con bufanda de lana, mirando a cámara sobre fondo amarillo',
    highlight: 'Compañero de sillón',
    status: 'adoptada',
    interestedCount: 11,
    publishedAt: hoursAgo(52),
  },
  {
    id: 'seed-canela',
    name: 'Canela',
    species: 'gato',
    ageLabel: '6 meses',
    size: 'pequeno',
    city: 'Salta',
    photoUrl: unsplash('photo-1573865526739-10659fec78a5'),
    photoAlt: 'Canela, gata naranja de pelo largo, estirada sobre una mesa de madera',
    highlight: 'Juguetona y sociable',
    status: 'publicada',
    interestedCount: 4,
    publishedAt: hoursAgo(31),
  },
  {
    id: 'seed-pipo',
    name: 'Pipo',
    species: 'roedor',
    ageLabel: '1 año',
    size: 'pequeno',
    city: 'Neuquén',
    photoUrl: unsplash('photo-1425082661705-1834bfd09dca'),
    photoAlt: 'Pipo, hámster dorado sentado sobre sus patas traseras comiendo',
    highlight: 'Va con jaula y accesorios',
    status: 'publicada',
    interestedCount: 1,
    publishedAt: hoursAgo(40),
  },
  {
    id: 'seed-tomas',
    name: 'Tomás',
    species: 'perro',
    ageLabel: '4 meses',
    size: 'mediano',
    city: 'Santa Fe',
    photoUrl: unsplash('photo-1552053831-71594a27632d'),
    photoAlt: 'Tomás, cachorro golden retriever sosteniendo una flor en el hocico',
    highlight: 'Primera vacuna al día',
    status: 'con-interesados',
    interestedCount: 9,
    publishedAt: hoursAgo(14),
  },
  {
    id: 'seed-mora',
    name: 'Mora',
    species: 'gato',
    ageLabel: '7 años',
    size: 'mediano',
    city: 'Bahía Blanca',
    photoUrl: unsplash('photo-1495360010541-f48722b34f7d'),
    photoAlt: 'Mora, gata atigrada de pelo largo, sentada en una escalera blanca',
    highlight: 'Busca una casa sin ruido',
    status: 'publicada',
    interestedCount: 2,
    publishedAt: hoursAgo(60),
  },
  {
    id: 'seed-trufa',
    name: 'Trufa',
    species: 'conejo',
    ageLabel: '2 años',
    size: 'pequeno',
    city: 'Tucumán',
    photoUrl: unsplash('photo-1452857297128-d9c29adba80b'),
    photoAlt: 'Trufa, conejo belier beige de orejas caídas, sobre el césped',
    highlight: 'Se lleva bien con gatos',
    status: 'publicada',
    interestedCount: 3,
    publishedAt: hoursAgo(70),
  },
  {
    id: 'seed-iggy',
    name: 'Iggy',
    species: 'reptil',
    ageLabel: '3 años',
    size: 'mediano',
    city: 'Corrientes',
    photoUrl: unsplash('photo-1504450874802-0ba2bcd9b5ae'),
    photoAlt: 'Iggy, iguana verde caminando sobre un piso claro',
    highlight: 'Terrario incluido',
    status: 'publicada',
    interestedCount: 1,
    publishedAt: hoursAgo(85),
  },
];
